stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: us.gcr.io/in-the-void/voidbot:$CI_COMMIT_TAG
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

Build Project:
  stage: build
  image: rust:1.33-slim-stretch
  script:
    - apt update && apt install --no-install-recommends -y libssl-dev pkg-config
    - cargo build --release
  cache:
    paths:
      - .cargo/
      - target/release
  artifacts:
    paths:
      - target/release/voidbot
  only:
    - tags

Deploy Project:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo "$GCLOUD_AUTH_KEY" | base64 -d | gcloud auth activate-service-account deploy@in-the-void.iam.gserviceaccount.com --key-file /dev/stdin
    - gcloud auth configure-docker
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - gcloud config set project in-the-void
    - gcloud compute instances update-container voidbot --container-image $IMAGE_NAME --zone us-west1-b
  only:
    - tags