[package]
name = "voidbot"
version = "0.1.0"
authors = ["Noah Shuart <shuart.noah.s@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.5"
lazy_static = "1.3.0"

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }